### ISSUE TITLE
USSEDP Patcher no longer works

### ISSUE THREAD

**Issue by edrzns** [The-Animonculory/Modding-Resources#4]
Tried today, and it seems patcher/downloader no longer wroks, as seen in the comments in nexus

Patcher ends with error:

`Started USSEDP

Starting Patching

Building Install Plan

Attempting login

Connected to Steam, logging in

Existing login keys found, reusing

Account is SteamGuard protected

Logged out

Got request for Auth Code

Attempting login

Connected to Steam, logging in

Existing login keys found, reusing

Logged into Steam

Steam has provided game information

Caching manifests

Getting Manifest 489833 - 4570833277049890269

Loading CDN servers

20 servers found

(Retry 1 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 100ms

(Retry 2 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 200ms

(Retry 3 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 400ms

(Retry 4 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 800ms

(Retry 5 of 5), got exception Response status code does not indicate success: 401 (Unauthorized)., waiting 1600ms

While running
Exception: System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetByteArrayAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Wabbajack.Networking.Steam.Client.<>c__DisplayClass52_0.<<GetAppManifest>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Common.CircuitBreaker.WithAutoRetryAsync[TR,TE](ILogger logger, Func`1 f, Nullable`1 delay, Nullable`1 multipler, Nullable`1 maxRetries)
   at Wabbajack.Networking.Steam.Client.GetAppManifest(UInt32 appId, UInt32 depotId, UInt64 manifestId)
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 304
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.Start() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 306
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_17() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 122
   at Patcher.ViewModels.MainWindowViewModel.<.ctor>b__72_3() in c:\oss\ussedp\Patcher\ViewModels\MainWindowViewModel.cs:line 120`

**Comment by Althro** [comment]
Which tutorial is this referenced in?

**Comment by edrzns** [comment]
Grass Lod Cache generation for 1.6.X
https://github.com/The-Animonculory/Modding-Resources/blob/main/Grass%20Lods.md

**Comment by Althro** [comment]
I've changed the link to the best of both worlds patcher which continues to work.
